const API_BASE='';
let token=localStorage.getItem('pepiko_internal_token')||'';
let user=JSON.parse(localStorage.getItem('pepiko_internal_user')||'null');
let currentPage='dashboard'; let selectedCustomerId=null; let currentRouteDetail='';
const pages=[['dashboard','Overview','⌂'],['users','Users & Roles','♙'],['customers','Customers','▦'],['products','Products Management','◈'],['plans','Plans & Pricing','◉'],['billing','Billing Operations','💳'],['support','Support Tickets','?'],['usage','Usage Monitoring','◷'],['reports','Risk Reports','▧'],['audit','Internal Audit Logs','≣'],['health','System Health','●']];
const routeBase='';
const pageRoutes={dashboard:'dashboard',users:'users',customers:'customers',products:'products',plans:'plans',billing:'billing',support:'support',usage:'usage',reports:'reports',audit:'audit',health:'health'};
const routePages=Object.fromEntries(Object.entries(pageRoutes).map(([page,route])=>[route,page]));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:4}); const date=d=>d?new Date(d).toLocaleString():'-';
const badge=v=>`<span class="status ${esc(String(v||'').toLowerCase())}">${esc(v||'-')}</span>`;
function brand(panel='Internal Admin'){return `<div class="login-brand"><div class="brand">pepiko<span class="brand-ai">.ai</span></div><div class="brand-panel">${panel}</div></div>`}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">No data yet</td></tr>`}</tbody></table>`}
function navPages(){return pages.filter(p=>p[0]!=='users'||['super_admin','ops_admin'].includes(user?.role))}
function statusType(kind){return kind===true||kind==='error'?'error':kind==='success'?'success':kind==='warning'?'warning':'information'}
function setStatus(msg='',kind='information'){const type=statusType(kind); const el=$('#status'); if(el){el.textContent=msg; el.className=`portal-alert ${type}`; el.style.display=msg?'flex':'none'}}
function setFormError(msg='',field=null,target='formError'){const el=typeof target==='string'?($(`#${target}`)||$(target)):target; $$('.field-invalid').forEach(x=>x.classList.remove('field-invalid')); if(!msg){if(el){el.textContent='';el.style.display='none'} return false} if(el){el.textContent=msg;el.className='portal-alert warning form-error';el.style.display='flex';el.scrollIntoView({block:'nearest'})}else setStatus(msg,'warning'); if(field){field.classList.add('field-invalid');field.focus?.()} return false}
function renderPageLoading(){const el=$('#content'); if(el)el.innerHTML='<div class="panel empty">Loading...</div>'}
function successMessage(path,method){if(path.includes('/auth/login'))return 'Signed in to the internal portal successfully.'; if(path.includes('/users/')&&path.endsWith('/reset-password'))return 'Internal user password was reset successfully.'; if(path.includes('/users'))return method==='POST'?'Internal user created successfully.':'Internal user role and access were updated.'; if(path.includes('/customers/')&&path.includes('/account'))return 'Customer account settings updated. API key access was adjusted if the account status changed.'; if(path.includes('/customers/')&&path.includes('/credits'))return 'Customer wallet credits adjusted and ledger entry recorded.'; if(path.includes('/customers/')&&path.includes('/enterprise-pricing'))return 'Enterprise pricing override saved for this customer.'; if(path.includes('/customers/')&&path.includes('/team/'))return 'Customer team member access updated.'; if(path.includes('/customers/')&&path.includes('/projects/'))return 'Customer project status updated.'; if(path.includes('/customers/')&&path.includes('/api-keys/'))return 'Customer API key status updated. The key access change is effective immediately.'; if(path.includes('/customers'))return method==='POST'?'Customer account created successfully.':'Customer record updated successfully.'; if(path.includes('/products/')&&path.endsWith('/publish'))return 'API product published. It is now visible in the customer portal.'; if(path.includes('/products/')&&(path.endsWith('/unpublish')||path.endsWith('/disable')))return 'API product unpublished. Customers will no longer see it as available.'; if(path.includes('/products'))return method==='DELETE'?'API product configuration deleted. It will no longer appear in internal product management.':method==='POST'?'API product created successfully.':'API product configuration updated.'; if(path.includes('/plans'))return method==='POST'?'Plan created successfully.':'Plan and pricing settings updated.'; if(path.includes('/billing'))return 'Billing records refreshed after the operation.'; if(path.includes('/support/tickets/'))return 'Support ticket updated. Customer-visible progress and notes were saved.'; const resource=path.split('?')[0].split('/').filter(Boolean).slice(-1)[0]||'request'; return `${method} ${resource.replaceAll('-',' ')} completed successfully.`}
async function api(path,opts={}){const headers=opts.headers||{}; if(token)headers.Authorization=`Bearer ${token}`; if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json'; const method=(opts.method||'GET').toUpperCase(); const res=await fetch(API_BASE+path,{cache:'no-store',...opts,headers}); let data=null; try{data=await res.json()}catch{} if(!res.ok){const err=new Error((data&&data.detail)||res.statusText); err.status=res.status; setStatus(err.message,true); throw err} if(method!=='GET')setStatus(opts.successMessage||successMessage(path,method),'success'); return data}
function routeForPage(id,detail=''){const route=pageRoutes[id]||pageRoutes.dashboard; return id==='customers'&&detail?`/${route}/${encodeURIComponent(detail)}`:`/${route}`}
function pageFromPath(path=location.pathname){const clean=path.replace(/\/+$/,''); if(clean==='')return 'dashboard'; return routePages[clean.replace(/^\/+/,'').split('/')[0]]||'dashboard'}
function routeDetailFromPath(path=location.pathname){const parts=path.replace(/\/+$/,'').replace(/^\/+/,'').split('/'); return parts.length>1?decodeURIComponent(parts.slice(1).join('/')):''}
function pushRoute(id,detail=''){const next=routeForPage(id,detail); if(location.pathname!==next)history.pushState({page:id,detail},'',next)}
function canAccessPage(id){return navPages().some(p=>p[0]===id)}
function normalizePage(id){return canAccessPage(id)?id:'dashboard'}
function logout(){localStorage.removeItem('pepiko_internal_token');localStorage.removeItem('pepiko_internal_user');location.href='/'}
async function login(e){e.preventDefault();setStatus('Signing in...');try{const d=await api('/api/internal/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});token=d.access_token;user=d.user;localStorage.setItem('pepiko_internal_token',token);localStorage.setItem('pepiko_internal_user',JSON.stringify(user));renderApp()}catch(err){setStatus(err.message,true)}}
function renderLogin(){document.body.innerHTML=`<div class="login-page"><section class="login-left">${brand('Internal Admin')}<div class="login-copy"><h1>Operate the Pepiko platform.</h1><p>Manage customers, products, billing, plans, credits, support tickets, customer account issues, usage, risk signals and internal audits.</p><div class="login-points"><div class="login-point"><div class="point-icon">🛠</div><div><h3>Operations-first</h3><p>Everything your internal team needs to keep customer-facing platform.pepiko.ai running.</p></div></div><div class="login-point"><div class="point-icon">◉</div><div><h3>Blue brand system</h3><p>Aligned with the platform portal UI and pepiko.ai dashboard design.</p></div></div></div></div><div class="login-preview"><div class="preview-top"><span class="preview-dot"></span><span class="preview-dot"></span><span class="preview-dot"></span></div><div class="preview-body"><div class="preview-side"><span class="preview-line"></span><span class="preview-line"></span><span class="preview-line"></span></div><div class="preview-main"><div class="preview-card"><strong>Customers</strong><div class="preview-chart"></div></div><div class="preview-card"><strong>Billing</strong><div class="preview-chart"></div></div></div></div></div></section><section class="login-right"><div></div><div class="login-form-wrap"><form class="login-form" onsubmit="login(event)"><h2>Internal sign in</h2><div class="field"><label>Email address</label><div class="input-wrap"><span>✉</span><input id="email" value="admin@pepiko.ai"></div></div><div class="field"><label>Password</label><div class="input-wrap"><span>●</span><input id="password" type="password" value="password123"></div></div><button class="btn primary" style="width:100%;min-height:60px">Sign in</button><div id="status" class="muted small" style="margin-top:16px"></div></form></div><div class="login-footer"><span>© 2026 Pepiko Internal</span><span>Default: admin@pepiko.ai / password123</span></div></section></div>`}
function shell(){document.body.innerHTML=`<div class="app"><aside class="sidebar">${brand('Internal Admin')}<div class="nav-group"><p class="nav-title">Operations</p>${navPages().map(p=>`<a class="nav-link" href="${routeForPage(p[0])}" data-page="${p[0]}"><span class="ico">${p[2]}</span>${p[1]}</a>`).join('')}</div><div style="margin-top:34px;padding-top:18px;border-top:1px solid var(--line)"><div class="small muted">Internal user</div><strong>${esc(user?.name||'')}</strong><div class="small muted" style="margin-top:8px">Role</div><strong>${esc(user?.role||'')}</strong><br><button class="btn" onclick="logout()" style="margin-top:14px;width:100%">Logout</button></div></aside><main class="main"><header class="topbar"><div class="search"><span>⌕</span><input placeholder="Search customers, products, tickets, invoices..."></div><div class="top-actions"><button class="btn" onclick="showPage('support')">Tickets</button><div class="user-menu"><div class="avatar">${esc((user?.name||'PA').split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><div class="user-name">${esc(user?.name||'')}</div><div class="user-role">${esc(user?.role||'')}</div></div></div></div></header><section class="content"><div id="pageHead"></div><div id="status" class="muted small"></div><div id="content"></div><div class="footer-line"><span>internal.pepiko.ai</span><span>Operations portal connected to platform-core-service</span></div></section></main></div><div id="modal" class="hidden"></div>`; $$('a.nav-link[data-page]').forEach(a=>a.onclick=e=>{e.preventDefault();showPage(a.dataset.page)});}
function head(title,desc,actions=''){ $('#pageHead').innerHTML=`<div class="page-head"><div class="page-title"><div class="breadcrumb">pepiko.ai internal / ${esc(title)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="page-actions">${actions}</div></div>`}
function activate(id){currentPage=id; $$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===id))}
async function showPage(id,{replace=false,skipRoute=false,detail=''}={}){id=normalizePage(id);currentRouteDetail=id==='customers'?detail:'';if(skipRoute&&location.pathname!==routeForPage(id,currentRouteDetail))history.replaceState({page:id,detail:currentRouteDetail},'',routeForPage(id,currentRouteDetail));if(!skipRoute){if(replace)history.replaceState({page:id,detail:currentRouteDetail},'',routeForPage(id,currentRouteDetail));else pushRoute(id,currentRouteDetail)}activate(id);setStatus('');renderPageLoading();try{if(id==='customers')await customers(currentRouteDetail);else await({dashboard,users,products,plans,billing,support,usage,reports,audit,health}[id]||dashboard)()}catch(e){setStatus(e.message,true)}}
function closeModal(){ $('#modal').className='hidden'; $('#modal').innerHTML='' }
function renderApp(){shell();currentPage=pageFromPath();const detail=currentPage==='customers'?routeDetailFromPath():'';showPage(currentPage,{replace:true,skipRoute:location.pathname===routeForPage(currentPage,detail),detail})}
window.addEventListener('popstate',()=>{if(token){const page=pageFromPath();showPage(page,{skipRoute:true,detail:page==='customers'?routeDetailFromPath():''})}});
